---
title: "Ek Okuma Önerileri"
---

Bu kitap tamamlandıktan sonra da akademi ve üniversite üzerine yazmayı sürdürdüm. Bu süreçte kaleme aldığım bazı metinler, tematik olarak kitabın tartıştığı meselelerle doğrudan ilişki kuruyor; ancak kitabın yazımından sonra ortaya çıktı. Birikim Online ve Yetkin Report gibi mecralarda yayımlanan bu yazıları, kitabın ana argümanlarını tamamlayan ve genişleten ek okumalar olarak burada başlıkları ve bağlantılarıyla birlikte kronolojik sırayla bir araya getirdim.

- [Özgür üniversite, makbul üniversitenin gölgesinde](https://yetkinreport.com/2025/07/20/ozgur-universite-makbul-universitenin-golgesinde/){target="_blank"}, Utku Perktaş, Yetkin Report, 20 Temmuz 2025.

- [Sahte Diploma, Temsil Krizi ve Üniversitenin Hafıza Kaybı](https://yetkinreport.com/2025/08/07/sahte-diploma-temsil-krizi-ve-universitenin-hafiza-kaybi/){target="_blank"}, Utku Perktaş, Yetkin Report, 7 Ağustos 2025.

- [Temsilin Yükü: Üniversiteyi Ayakta Tutan Gerçek Değer Nedir?](https://birikimdergisi.com/guncel/12129/temsilin-yuku-universiteyi-ayakta-tutan-gercek-deger-nedir){target="_blank"}, Utku Perktaş, Birikim Online, 8 Ağustos 2025.

- [Bilimin Görünmeyen Yüzü: Zorbalığın Sessizliğinden Bilimin Eşitlik Arayışına](https://yetkinreport.com/2025/10/12/bilimin-gorunmeyen-yuzu-zorbaligin-sessizliginden-bilimin-esitlik-arayisina/), Utku Perktaş, Yetkin Report, 12 Ekim 2025.

- [Güvene Tutunmak: Aidiyet, Etik ve Kurumsal Zafiyet Arasında Türkiye’de Akademi](https://birikimdergisi.com/guncel/12227/guvene-tutunmak-aidiyet-etik-ve-kurumsal-zafiyet-arasinda-turkiyede-akademi), Utku Perktaş, Birikim Online, 23 Kasım 2025.

- [Fahrenheit 98.6: Üniversite Nasıl Çözülür?](https://birikimdergisi.com/guncel/12343/fahrenheit-98-6-universite-nasil-cozulur){target="_blank"}, Utku Perktaş, Birikim Online, 13 Ocak 2026.

- [Üç Yıllık Lisans Modeli: Yoğunlaştırılmış mı, Sıkıştırılmış mı?](https://yetkinreport.com/2026/01/23/uc-yillik-lisans-modeli-yogunlastirilmis-mi-sikistirilmis-mi/){target="_blank"}, Utku Perktaş, Yetkin Report, 23 Ocak 2026.

- [Akran Zorbalığı Sicili ve Üniversiteye Kabulde Güney Kore Örneği](https://yetkinreport.com/2026/02/10/akran-zorbaligi-sicili-ve-universiteye-kabulde-guney-kore-ornegi/){target="_blank"}, Utku Perktaş, Yetkin Report, 10 Şubat 2026.

