---
title: "Gündüz Vassaf'ın Önsözü"
---

# Utku Perktaş’ın Çağrısı

*Gündüz Vassaf*

Üniversite ufuk açacağına devlet ve sermayenin hizmetinde.
Saygınlığının kamuflajında kendi masalına kendisi inanırken özerkliğini yitirdi.

Özgürlüğünü kendi eliyle sansürler oldu.

Hocalar kapıkullaştı, öğrencileri aldattı.

Alıştık.

Yıl 1930. Abraham Flexner. Princeton’da Institute of Advanced Studies’i kurar.  Çeşitli dallardan akademisyenler, ders vermek ve idari işlerden bir süre uzak kalıp burada ne merak ediyorlarsa onu araştırır.  Bilimsel keşiflerden de öte devrim niteliğindeki teknolojik atılımlara yol açan bu merkez Einstein, Oppenheimer, von Neumann,  Geertz, ve Gödel gibilere ev sahipliği yapar.  Flexner bu mealde “İşe yaramayan bilgilerin yararlığı’’ kitabını da  yayınlar.  O işe yaramayan şeylerdir ufkumuzu açıp yaşamımızı anlamlandıran. Yoksa ne kuantum mekaniği bilinir ne de bilgisayar çipleri bulunurdu.

Oysa, “Tornavidanın ne işe yaradığı’’ sathiliğinde  bir bakışın üniversiteye hakim olduğu günlerde yaşıyoruz.

Doktoramı  aldığımda çoğumuzun  üniversitenin temel işlevinin ders vermekten de öte, araştırma yapılması olduğunu bilmiyorduk. Hoca olmamı, arkadaşlarımın “Ne güzel uzun yaz tatillerin olacak,’’ sözleri etkilemişti. Düzenin benden beklentisinin öğrencileri mesleklerine hazırlamak ve devletin  ideolojilerine itaatkar gençlik imal etmek peşinde olduğunu öğrenmem uzun sürmedi.

Almanya’dan zamanında dünyaya örnek Humboldt üniversite anlayışından günümüze kalan koca bir kurumsal yıkım.  Başarısız meslek okullarına dönüştürülen üniversitenin olmazsa olmazı, akademik özgürlük ve üniversite özerkliği bugün pek kimsenin umurunda değil.

Hitler döneminde faşizmin gadrine uğrayan Alman üniversiteleri bugün hala belini doğrultamadı. Nazi rejiminden kaçan hocaların Türkiye’de temellerini attığı üniversitenin çöküşünün sorumlularıysa biziz.

12 Eylül devlet terörü günlerinde Evren cuntası tarafından İhsan Doğramacı aracılığıyla YÖK kurulduktan sonra, hocaların ihbarlarla atılması, kimilerinin de istifa etmesiyle, üniversite, “Biz kaleyi içerden koruyoruz’’ diyen kapıkullaştırılmış hocalara kalmıştı. Aradan geçen yarım asırda Türkiye’nin nisbi demokratik ortamlarına ve Tansu Çiller ve Erdal İnönü gibi profesörlerin Başbakan ve Başbakan Yardımcısı olmalarına rağmen, YÖK’e dokunmaya kimse yanaşmadı, maaşlarına talim eden hocalar idare-i maslahatlarını sürdürdü.

Tek ses, elli yıl sonra, Boğaziçi Üniversitesi’nde öğrencilerden ve onların peşinde gitmek konumunda kalan hocalardan, ancak gene YÖK’e tabi olacak rektör seçimine indirgenerek geldi. Türkiye hala üniversitelerine sahip çıkamayanların bedelini ödüyor. 
Bu hale gelmemizde tek müsebbip devlet değil. 
Sabancı, Koç gibi şirketler yüksek maaşlar ödeyerek açtıkları kurumlara transfer ettikleri hocalarla, ülkenin yerleşik üniversitelerinde süregelen akademik geleneği sabote ettiler.

Dönüm noktasındayız.

Çin, Rusya gibi  herhangi bir dikta rejimiyle ezilen ülkeler akademik özgürlük ve özerkliği tarihlerinde görmedi. Bugün ABD’de Harvard ve diğer üniversitelerin özgürlük ve özerkliklerinin  devlet saldırısına uğramasıysa  düşün yaşamımızda yeni bir ortaçağa karanlığının habercisi. Kanada, İngiltere ve kıta Avrupa’sında  üniversitelerin buna  seyirci kalmaktan öte, “ABD’nin kaybı benim kazancımdır’’ opurtünizminde kolları sıvayıp hocalara  bize gelin diye iş tekliflerine soyunmalarıysa ibret verici.

Tarihte kaç defa gördük.

Hitler’in  seçimle iktidara geldikten sonra ilk güç denemesi üniversite kıyımıydı. Ardından toplumun uyumcu edilgenliğinde ona bütün yollar açıldı. 

Totaliter populist rejimlerde  en güçlü muhalefet üniversitelerle entellektüellerken,  onlara karşı gaza getirilip iktidara güç veren de geniş kitleler değil mi?

Faşizm geldiğinde topla tüfekle değil, bizim sessizliğimizde, populist sloganlarla kitlelerin omuzunda yükseliyor.

Yapay zekanın uygarlığımızı nasıl etkileyeceğinin endişe verici belirsizliğinde akademik özgürlük ve üniversite özerkliğine sahip çıkmayan hocalarla öğrenciler, kritik düşüncenin silinip gideceği totaliter bir geleceğe davetiye çıkarmaktalar.

Uyur gezer konumunda üniversitenin temel değerlerinin bırakın korunması, unutulmuşken, Utku Perktaş, günümüz koşullarında nice riski göze alırken, kimi meslektaşlarınınsa   ‘’Bu da nereden çıktı,’’ diye bakacağı  kitabı bize bir çağrı niteliğinde. Neyi kaybetmekte olduğumuzun bilgisinden öte vicdanımıza seslenirken, yüksek öğrenim adına kendimizi aldattığımız kurumların olmazsa olmaz temellerinin, akademik özgürlük ve üniversite  özerkliğinin teker teker altını çizmekte.
 
Gündüz Vassaf

İstanbul

Haziran, 2025.
